### **SNP intersection (venn)**

```{r, eval = F}
fls <- here("batches123_04_FinalVCF/output/") %>% list.files(pattern = "*.snpIDs")

snp_ids <- lapply(fls, function(fl){
  ln <- str_remove(fl, "cohort_biallelicSNPs_VQSR95_PASS_AddedMissingness.recode.filtered.") %>% 
    str_remove(".snpIDs")
  d <- vroom(here("batches123_04_FinalVCF/output",fl), col_names = F) %>% mutate(line = ln, snp_id = paste0(X1,"_",X2))
  return(d)
})

names(snp_ids) <- str_remove(fls, "cohort_biallelicSNPs_VQSR95_PASS_AddedMissingness.recode.filtered.") %>% 
    str_remove(".snpIDs")


all_ids <- snp_ids %>% bind_rows() %>% select(-line, -X1, -X2) %>% unique() %>% unlist()

sets <- data.frame(ids = all_ids,
		   duk = (all_ids %chin% snp_ids$DUK$snp_id),
		   duc = (all_ids %chin% snp_ids$DUC$snp_id),
		   du6 = (all_ids %chin% snp_ids$DU6$snp_id),
		   du6p = (all_ids %chin% snp_ids$DU6P$snp_id),
		   duhlb = (all_ids %chin% snp_ids$DUhLB$snp_id),
		   fztdu = (all_ids %chin% snp_ids$FZTDU$snp_id))

write.csv(sets, here("00_dashboard/data","snp_id_sets.csv"))

```

```{r}
set_dat <- vroom(here("00_dashboard/data","snp_id_sets.csv")) %>% as.data.frame()

rownames(set_dat) <- set_dat$ids

set_dat <- set_dat %>% dplyr::select(duc,duk,du6,du6p,duhlb,fztdu)

xxx <- set_dat[1:2000,]

venn(xxx, zcolor = brewer.pal(n = 7, name = "Set1"))
```

### **SNP intersection (upset)**

```{r, fig.width=12, fig.height=5}
set_dat_bool <- data.frame(
  duk = as.integer(set_dat$duk),
	duc = as.integer(set_dat$duc),
	du6 = as.integer(set_dat$du6),
	du6p = as.integer(set_dat$du6p),
	duhlb = as.integer(set_dat$duhlb),
	fztdu = as.integer(set_dat$fztdu)
	)

rownames(set_dat_bool) <- rownames(set_dat)

upset(set_dat_bool, 
      nsets = 6, 
      nintersects = 62,
      number.angles = 45, 
      sets = c("fztdu","duhlb","du6p","du6","duc","duk"), 
      keep.order = T)
```

> 6-group intersection excluded

# missingness
```{r}
# per line summaries
gt_tab_long <- gt_tab %>%
  melt(id.vars = c("CHROM", "POS"), variable.name = "sample_id", value.name = "GT") %>%
  left_join(sample_info, by = "sample_id")

gt_tab_long %>% group_by(target_cvg, Linie) %>% summarise(n_miss = sum(GT == "./."))

gt_tab_long %>% group_by(Linie) %>% summarise(n_miss = sum(GT == "./."))

# Account for coverage

get_n_miss_by_cvg <- function(l,cvg){
  i <- sample_info$Linie == l & sample_info$target_cvg == cvg
  i_col <- names(gt_tab) %in% sample_info$sample_id[i]
  gt_tab[,i_col] %>% apply(1,function(row_x) sum(row_x == "./."))
}

miss_cts_30x <- data.frame(
  DUK = get_n_miss_by_cvg("DUK","30x"),
  DUC = get_n_miss_by_cvg("DUC","30x"),
  DU6 = get_n_miss_by_cvg("DU6","30x"),
  DU6P = get_n_miss_by_cvg("DU6P","30x"),
  DUhLB = get_n_miss_by_cvg("DUhLB","30x"),
  FZTDU = get_n_miss_by_cvg("FZTDU","30x")
) %>% mutate(target_cvg = "30x")

miss_cts_5x <- data.frame(
  DUK = get_n_miss_by_cvg("DUK","5x"),
  DUC = get_n_miss_by_cvg("DUC","5x"),
  DU6 = get_n_miss_by_cvg("DU6","5x"),
  DU6P = get_n_miss_by_cvg("DU6P","5x"),
  DUhLB = get_n_miss_by_cvg("DUhLB","5x"),
  FZTDU = get_n_miss_by_cvg("FZTDU","5x")
) %>% mutate(target_cvg = "5x")


miss_cts_by_cvg <- bind_rows(miss_cts_30x, miss_cts_5x) %>%
  melt(id.vars = "target_cvg", variable.name = "Line", value.name = "miss_counts")

png("../figures_tables/miss_cts_by_cvg.png", 
    width = 3000, height = 2000, units = "px", res = 300)
miss_cts_by_cvg %>%
  # Visualize
  ggplot(aes(x = miss_counts, after_stat(count), color = target_cvg)) +
  geom_density() +
  facet_wrap(~Line, ncol = 2, strip.position = "right") +
  theme_grey(base_size = 15) +
  scale_x_continuous(breaks = seq(0,30,1)) +
  xlab("missing counts per SNP")
dev.off()  


```

