---
title: "WGS DU-mice"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
---


```{r results="asis"}
cat("
<style>
caption {
      color: black;
      font-weight: bold;
      font-size: 1.0em;
    }
</style>
")
```

```{r libraries}
library(dplyr)
library(here)
library(stringr)
library(ggplot2)
library(ape)
```


```{r sample_info_and_genome_length, include=F}
sample_info <- read.csv(here("sample_info/sample_info_batch1_batch2.csv")) %>% 
  dplyr::select(Linie, sample_id) %>% 
  mutate(target_cvg = "30x") %>% 
  bind_rows(
    read.csv(here("sample_info/sample_info_batch3/sample_info.csv")) %>% 
      dplyr::select(Linie,name) %>% 
      dplyr::rename(sample_id = name) %>% 
      mutate(sample_id = str_remove(sample_id, "-S1"), target_cvg = "5x")
  ) %>% 
  mutate(Linie = ifelse(Linie == "HLB", "DUhLB",Linie))

#http://www.ensembl.org/Mus_musculus/Info/Annotation 
genome_length <- 2730871774 # genome length (Golden Path Length	) 
```

```{r pca_data, include=F}

pc_pct <- read.csv(here("batches123_06_genetic_structure/data/pc_pct_full_snp_set.csv")) %>% dplyr::select(-X)

pc_eigenscores <- read.csv(here("batches123_06_genetic_structure/data/pc_eigenscores_full_snp_set.csv")) %>% 
  dplyr::select(-X) %>% 
  mutate(sample.id = str_remove(sample.id, "-L1")) %>% 
  left_join(sample_info, by = c("sample.id"="sample_id")) %>% 
  dplyr::select(Linie, sample.id, target_cvg, everything()) %>% 
  mutate(Linie = factor(Linie, levels = c("DUK","DUC","DU6","DU6P","DUhLB","FZTDU")))
  
```

```{r make_ancestry_barplot_function}
make_ancestry_barplot <- function(k,q_fl){

#k=5 
#q_fl=here("batches123_06_genetic_structure/scripts/cohort_biallelicSNPs_VQSR95_PASS_AddedMissingness.recode.filtered.ldpruned.5.Q")

  k_dat <- read.table(q_fl) %>% 
    bind_cols(
      dplyr::select(fam_fl, V2) %>% dplyr::rename(sample_id = V2)
      ) %>% 
    mutate(sample_id = str_remove(sample_id, "-L1")) %>% 
    left_join(sample_info, by = "sample_id") %>% 
    reshape2::melt(id.vars = c("sample_id","Linie","target_cvg")) %>% 
    mutate(Linie = factor(Linie, levels = c("FZTDU","DUK","DUC","DU6","DU6P","DUhLB"))) %>% 
    arrange(Linie, sample_id)
  
  k_dat <- k_dat %>% 
    mutate(sample_id = factor(sample_id, levels = unique(k_dat$sample_id)))

  p <- k_dat %>% 
        ggplot(aes(x = sample_id, y = value,fill = variable)) +
          geom_bar(stat = "identity", position = "stack") +
          theme_bw(base_size = 20) +
          theme(
            axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
            legend.position = "none",
            plot.title = element_text(hjust = 0.5)
            ) +
          xlab(NULL) +
          ylab("Ancestry Fraction") +
          annotate("text",x = seq(12.5,150,25), y = 1.02, label = levels(k_dat$Linie), size = 8) +
          ggtitle(paste0("K=",k)) #+
          #ggsave("tst.png", height = 7, width = 15)
  return(p)
}
```

Genetic_Str
====================================

Column {.tabset}
----------------

### PC1 - PC2
```{r, fig.width = 5, fig.height=7}
p1 <- pc_eigenscores %>% 
        ggplot(data = ., aes(x=PC1,y=PC2,color=Linie)) +
          geom_point() +
          theme_bw(base_size = 15) +
          theme(legend.title = element_blank())

p2 <- pc_eigenscores %>% 
        mutate(gp = paste(Linie, target_cvg, sep = "_")) %>% 
        ggplot(data = ., aes(x=PC1,y=PC2,color=gp)) +
          geom_point() +
          theme_bw(base_size = 15) +
          theme(legend.title = element_blank())
  
gridExtra::grid.arrange(p1,p2, ncol = 1) 

rm(p1,p2)
```

```{r eval = FALSE, export_for_paper}
png(here("00_dashboard/for_manuscript/PC1_PC2_full_SNP_set.png"), res = 300, height = 2000, width = 2500, units = "px")
pc_eigenscores %>% 
  ggplot(data = ., aes(x=PC1,y=PC2,color=Linie)) + 
    geom_point(size = 4, alpha = 0.7) + 
    theme_bw(base_size = 20) + 
    theme(legend.title = element_blank()) +
    # colors based on palette Dark2 used later for admixture
    scale_color_manual(breaks = c("DUK","DUC","DU6","DU6P","DUhLB","FZTDU"),
                       values = c("#7570B3", "#66A61E", "#1B9E77", "#D95F02",  "#E7298A",  "black"))
dev.off()

```

### PC2 - PC3
```{r, fig.width = 5, fig.height=7}
p1 <- pc_eigenscores %>% 
        ggplot(data = ., aes(x=PC2,y=PC3,color=Linie)) +
          geom_point() +
          theme_bw() +
          theme(legend.title = element_blank())

p2 <- pc_eigenscores %>% 
        mutate(gp = paste(Linie, target_cvg, sep = "_")) %>% 
        ggplot(data = ., aes(x=PC2,y=PC3,color=gp)) +
          geom_point() +
          theme_bw() +
          theme(legend.title = element_blank())
  
gridExtra::grid.arrange(p1,p2, ncol = 1) 

rm(p1,p2)
```

### PC3 - PC4
```{r, fig.width = 5, fig.height=7}
p1 <- pc_eigenscores %>% 
        ggplot(data = ., aes(x=PC3,y=PC4,color=Linie)) +
          geom_point() +
          theme_bw() +
          theme(legend.title = element_blank())

p2 <- pc_eigenscores %>% 
        mutate(gp = paste(Linie, target_cvg, sep = "_")) %>% 
        ggplot(data = ., aes(x=PC3,y=PC4,color=gp)) +
          geom_point() +
          theme_bw() +
          theme(legend.title = element_blank())
  
gridExtra::grid.arrange(p1,p2, ncol = 1) 

rm(p1,p2)
```

### PC4 - PC5
```{r, fig.width = 5, fig.height=7}
p1 <- pc_eigenscores %>% 
        ggplot(data = ., aes(x=PC4,y=PC5,color=Linie)) +
          geom_point() +
          theme_bw() +
          theme(legend.title = element_blank())

p2 <- pc_eigenscores %>% 
        mutate(gp = paste(Linie, target_cvg, sep = "_")) %>% 
        ggplot(data = ., aes(x=PC4,y=PC5,color=gp)) +
          geom_point() +
          theme_bw() +
          theme(legend.title = element_blank())
  
gridExtra::grid.arrange(p1,p2, ncol = 1) 

rm(p1,p2)
```

### PC5 - PC6
```{r, fig.width = 5, fig.height=7}
p1 <- pc_eigenscores %>% 
        ggplot(data = ., aes(x=PC5,y=PC6,color=Linie)) +
          geom_point() +
          theme_bw() +
          theme(legend.title = element_blank())


p2 <- pc_eigenscores %>% 
        mutate(gp = paste(Linie, target_cvg, sep = "_")) %>% 
        ggplot(data = ., aes(x=PC5,y=PC6,color=gp)) +
          geom_point() +
          theme_bw() +
          theme(legend.title = element_blank())
  
gridExtra::grid.arrange(p1,p2, ncol = 1) 

rm(p1,p2)
```

```{r export_pc5_pc6_for_for_manuscript, eval = FALSE}
png(here("00_dashboard/for_manuscript/PC5_PC6_full_SNP_set.png"), res = 300, height = 2000, width = 2500, units = "px")
pc_eigenscores %>% 
  ggplot(data = ., aes(x=PC5,y=PC6,color=Linie)) + 
    geom_point(size = 4, alpha = 0.7) + 
    theme_bw(base_size = 20) + 
    theme(legend.title = element_blank()) +
    # colors based on palette Dark2 used later for admixture
    scale_color_manual(breaks = c("DUK","DUC","DU6","DU6P","DUhLB","FZTDU"),
                       values = c("#7570B3", "#66A61E", "#1B9E77", "#D95F02",  "#E7298A",  "black"))
dev.off()
```

### Scree Plot
```{r, fig.width = 7, fig.height=7}
pc_pct %>% 
  ggplot(aes(x=PC,y=varprop)) +
    geom_bar(stat = "identity") +
    xlab("Principal Component") +
    ylab("% Variance") +
    scale_x_continuous(breaks = 1:7) +
    theme_bw()
```

### Hierarchical Clustering 
```{r prepare_dendrogram_data}
dend <- readRDS(here("batches123_06_genetic_structure/data/dendrogram_full_snp_set.rds")) %>% as.hclust()

# change labels to group to avoid legend
#identical(sample_info[,"sample_id"], str_remove(dend[["labels"]], "-L1")) #check order of labels is the same! yes!
dend[["labels"]] <- sample_info$Linie
```


```{r, fig.width = 10, fig.height=5} 
# colors based on palette Dark2 used later for admixture
colrs <- c("#7570B3","#66A61E", "#1B9E77", "#D95F02", "#E7298A", "black")
names(colrs) <- c("DUK","DUC","DU6","DU6P","DUhLB", "FZTDU")

# make 6 clusters
clus6 <- cutree(dend, 6)

# add colors by cluster, matching line with corresponding color
colrs_tip <- colrs[names(clus6)]

plot(as.phylo(dend), 
     type = "fan", 
     cex = 0.6,
     no.margin = TRUE,
     tip.color = colrs_tip)

# good reference: http://www.sthda.com/english/wiki/beautiful-dendrogram-visualizations-in-r-5-must-known-methods-unsupervised-machine-learning
```


```{r for_paper_HC, evel = F} 

png(here("00_dashboard/for_manuscript/HC_full_set.png"), res = 300, height = 2200, width = 2200, units = "px")

# colors based on palette Dark2 used later for admixture
colrs <- c("#7570B3","#66A61E", "#1B9E77", "#D95F02", "#E7298A", "black")
names(colrs) <- c("DUK","DUC","DU6","DU6P","DUhLB", "FZTDU")

# make 6 clusters
clus6 <- cutree(dend, 6)

# add colors by cluster, matching line with corresponding color
colrs_tip <- colrs[names(clus6)]

plot(as.phylo(dend), 
     type = "fan", 
     cex = 1,
     no.margin = TRUE,
     tip.color = colrs_tip)

dev.off()

```

### Admixture  
```{r import_fam_info}
# About sample ordering: https://www.biostars.org/p/221817/

fam_fl <- read.table(here("batches123_06_genetic_structure/data/cohort_biallelicSNPs_VQSR95_PASS_withmissingness.filtered.fam"))
```

```{r barplot_k5, fig.width=20, fig.height=7}
make_ancestry_barplot(
  k=5, 
  q_fl=here("batches123_06_genetic_structure/scripts/cohort_biallelicSNPs_VQSR95_PASS_withmissingness.filtered.5.Q")
) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) 
```


```{r for_paper_admix, eval = F}

k=5 
q_fl=here("batches123_06_genetic_structure/scripts/cohort_biallelicSNPs_VQSR95_PASS_withmissingness.filtered.5.Q")

k_dat <- read.table(q_fl) %>% 
  bind_cols(
    dplyr::select(fam_fl, V2) %>% dplyr::rename(sample_id = V2)
    ) %>% 
  mutate(sample_id = str_remove(sample_id, "-L1")) %>% 
  left_join(sample_info, by = "sample_id") %>% 
  reshape2::melt(id.vars = c("sample_id","Linie","target_cvg")) %>% 
  mutate(Linie = factor(Linie, levels = c("FZTDU","DUK","DUC","DU6","DU6P","DUhLB"))) %>% 
  arrange(Linie, sample_id)

k_dat <- k_dat %>% 
  mutate(sample_id = factor(sample_id, levels = unique(k_dat$sample_id)))


png(here("00_dashboard/for_manuscript/admixture_full_snp_set.png"), res = 300, height = 800, width = 1400, units = "px")

k_dat %>% 
  ggplot(aes(x = sample_id, y = value,fill = variable)) +
  geom_bar(stat = "identity", position = "stack", width = 1) +
  theme_bw(base_size = 12) +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5)
  ) +
  xlab(NULL) +
  ylab("Ancestry Fraction") +
  ggtitle(paste0("K=",k)) +
  scale_y_continuous(expand = c(0.005,0.005), breaks = seq(0,1,0.2)) +
  scale_fill_brewer(palette = "Dark2") +
  facet_grid(~Linie, scales = "free") +
  theme(panel.spacing = unit(1/15, "lines"),
        strip.background = element_blank(), 
        panel.border = element_blank(),
        panel.grid = element_blank(),
        axis.text.x = element_blank()) 


dev.off()
```




